apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: mongodb-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  apiGroupOf: rbac.authorization.k8s.io
  name: mongodb-role