apiVersion: v1
kind: Secret
metadata:
  name: pycrest-global-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.global.mongodb.uri | quote }}
  MONGODB_DB: {{ .Values.global.mongodb.db | quote }}
  JWT_SECRET: {{ .Values.global.jwt.secret | quote }}
  JWT_SECRET_KEY: {{ .Values.global.jwt.secret | quote }}
  JWT_ALGORITHM: {{ .Values.global.jwt.algorithm | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.global.jwt.expireMinutes | quote }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.global.internalServiceToken | quote }}
  AUTH_SERVICE_URL: {{ .Values.global.serviceUrls.auth | quote }}
  LOAN_SERVICE_URL: {{ .Values.global.serviceUrls.loan | quote }}
  EMI_SERVICE_URL: {{ .Values.global.serviceUrls.emi | quote }}
  WALLET_SERVICE_URL: {{ .Values.global.serviceUrls.wallet | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.global.serviceUrls.payment | quote }}
  VERIFICATION_SERVICE_URL: {{ .Values.global.serviceUrls.verification | quote }}
  ADMIN_SERVICE_URL: {{ .Values.global.serviceUrls.admin | quote }}
  MANAGER_SERVICE_URL: {{ .Values.global.serviceUrls.manager | quote }}
  AUDIT_SERVICE_URL: {{ .Values.global.serviceUrls.admin | quote }}