apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pycrest-uploads-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: 20Gi